added support for ROS 2 Iron
ros-realtime/ros-realtime-rpi4-image pull request #64
Opened 2023-05-20 21:01 UTC by razr

2023-05-22 07:12 UTC, LanderU approved these changes
LGTM!

2023-05-22 15:11 UTC, carlossvg commented
Script to generate release plot: https://github.com/ros-realtime/ros_realtime_benchmarks_config/tree/main/cyclictest

2023-05-22 15:19 UTC, nightduck commented on image_builder/data/jammy-rt-iron/rootfs/etc/apt/sources.list.d/ros2.list
This link should be changed to

    deb [arch=arm64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu/ iron main

The link will be valid Tuesday, May 23rd, after Iron releases

2023-05-25 01:32 UTC, shuhaowu approved these changes
Do you want to add this to `.github/workflows/build.yml` so we can build it on Github CI as well?

2023-05-25 01:32 UTC, shuhaowu commented on Makefile
> +jammy-rt-iron:
Can you add this target to `.PHONY`?

2023-05-25 01:33 UTC, shuhaowu commented
Latency analysis scripts: https://github.com/ros-realtime/ros-realtime-rpi4-image/tree/master/latency-analysis

2023-05-30 07:42 UTC, LanderU requested changes

2023-05-30 07:42 UTC, LanderU commented on image_builder/data/jammy-rt-iron/rootfs/etc/apt/sources.list.d/ros2.list
> +deb [arch=arm64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2-testing/ubuntu jammy main
```suggestion
deb [arch=arm64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu jammy main
```

2024-07-16 17:22 UTC, shuhaowu commented
@razr I'm closing  this as we discussed to move towards Jazzy + Noble.

2024-07-16 17:22 UTC, closed without merging